# Generated by Django 4.1.4 on 2022-12-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Upload_Image',
        ),
    ]
