# Generated by Django 4.1.4 on 2022-12-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_image_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
