# Generated by Django 4.1.4 on 2022-12-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_upload_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processed_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
