# Generated by Django 4.1.4 on 2022-12-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_processed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processed_image',
            name='save_image',
            field=models.ImageField(upload_to='processed_images'),
        ),
    ]
