# Generated by Django 4.1.4 on 2022-12-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_processed_image_save_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='processed_image',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
