# Generated by Django 4.1.4 on 2022-12-31 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_processed_image_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processed_image',
            name='username',
        ),
        migrations.AddField(
            model_name='processed_image',
            name='user',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
